# Prof's Gradle CI, updated for 2025 runners + lab echo
name: Java CI with Gradle

on:
  push:
    branches: [ master, main ]   # supports either default branch
  pull_request:
    branches: [ master, main ]

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print class message  # <- lab requirement
        run: echo "Hi, I am from COSC 1209 class"

      - name: Set up JDK 11 (Temurin)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # ---- Docker build & push to Docker Hub (optional but in prof's file) ----
      # Requires: a Dockerfile at repo root, and two repo secrets:
      #   DOCKER_USERNAME and DOCKER_PASSWORD (Docker Hub credentials)
      - name: Build and Push Docker Image
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: kowz97/cicdrunner    # <-- change this
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
